=== thuyle2000/2206.M1/1.MLJ/employee.xsd
<?xml version="1.0"?>
<!--
mo ta cau truc ho so nhan vien
moi nhan vien bao gom :
- thuoc tinh id (chuoi ky tu)
- du lieu:
     ho ten (chuoi)
     gioi tinh (boolean) 
     ngay sinh (date)
     luong (so nguyen)
     chuc vu (chuoi)
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    
    <!--    dinh nghia kieu du lieu [personInfo]-->
    <xs:complexType name="personInfo">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="gender" type="xs:boolean" />
            <xs:element name="dob" type="xs:date" />
            <xs:element name="salary" type="xs:integer" />
            <xs:element name="position" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" />
    </xs:complexType>
    
    
<!--    dinh nghia root node cua ho so nhan vien -->
    <xs:element name="employee-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" 
                            type="personInfo"
                            minOccurs="3"
                            maxOccurs="unbounded"  />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== thuyle2000/2206.M1/1.MLJ/d02_employee_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
ho so nhan vien
-->



<employee-list
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='employee.xsd'>
    <employee id="nv100">
        <name>Cat tuong</name>
        <gender>false</gender>
        <dob>2003-08-31</dob>
        <salary>1200</salary>
        <position>Nhan vien</position>
    </employee>
    
    <employee id="nv101">
        <name>Van An</name>
        <gender>true</gender>
        <dob>2000-12-31</dob>
        <salary>2000</salary>
        <position>Truong Phong</position>
    </employee>
    
    <employee id="nv102">
        <name>Phuoc tho</name>
        <gender>true</gender>
        <dob>2004-06-22</dob>
        <salary>1</salary>
        <position>Giam Doc</position>
    </employee>

</employee-list>
