=== thuyle2000/2206.M1/1.MLJ/student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
mo ta cau truc ho so sinh vien.
moi sinh vien bao gom cac fields: 
    ho ten, nam sinh, gioi tinh, trung tam 
va thuoc tinh ma so (duy nhat) cua sinh vien
-->

<!ELEMENT student-list (student+)>
<!ELEMENT student (fullname, yob, gender, center)>
<!ELEMENT fullname (#PCDATA)>
<!ELEMENT yob (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT center (#PCDATA)>
<!ATTLIST student id ID #REQUIRED>
<!ATTLIST center name (Aptech|Arena) #REQUIRED>

=== thuyle2000/2206.M1/1.MLJ/d02_student2_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!DOCTYPE student-list SYSTEM 'student.dtd'
[    
    <!ENTITY hn "Ha noi">
    <!ENTITY sg "Saigon">
    <!ENTITY dn "Da nang">
]
>
<student-list>
    <student id="sv1">
        <fullname>Cat Tuong</fullname>
        <yob>2003</yob>
        <gender> nu </gender>
        <center name="Aptech">&hn;</center>
    </student>
    
    <student id="sv2">
        <fullname>Van An</fullname>
        <yob>2004</yob>
        <gender> nam </gender>
        <center name="Arena"> &sg;</center>
    </student>
</student-list>
